-- Generated by scripts/onboard.ts from config/tenants/alcadent.json.
-- Do not edit by hand: edit the profile and re-run `npm run seed:build`.
-- Every statement is an upsert, so applying this twice is a no-op.

-- Tenant --------------------------------------------------------------------
insert into public.tenants (id, slug, name, vertical, plan, status, timezone, locale)
values (
  '11111111-1111-4111-8111-111111111111',
  'alcadent',
  'Alcadent India',
  'dental_clinic',
  'growth'::public.plan_tier,
  'active'::public.tenant_status,
  'Asia/Kolkata',
  'en-IN'
)
on conflict (slug) do update set
  name = excluded.name,
  vertical = excluded.vertical,
  plan = excluded.plan,
  status = excluded.status,
  timezone = excluded.timezone,
  locale = excluded.locale;

-- Configuration -------------------------------------------------------------
insert into public.tenant_config (tenant_id, business, hours, brand, channels, escalation, limits)
values (
  (select id from public.tenants where slug = 'alcadent'),
  '{"legal_name":"Alcadent India","tagline":"Kids & Adult Dentistry","lead_clinician":"Dr. Anukriti Gupta, Chief Pediatric Dental Surgeon","experience_years":14,"address":"F-49, First Floor, Elan Miracle Mall, Sector 84, Gurugram 122004","maps_url":"https://maps.google.com/?q=Elan+Miracle+Mall+Sector+84+Gurugram","whatsapp":"+919889885908","highlights":["Painless injection technique","Conscious sedation for anxious children","Open 7 days"]}'::jsonb,
  '{"mon":["10:00","20:00"],"tue":["10:00","20:00"],"wed":["10:00","20:00"],"thu":["10:00","20:00"],"fri":["10:00","20:00"],"sat":["10:00","20:00"],"sun":["11:00","17:00"]}'::jsonb,
  '{"status":"derived_from_instagram_unconfirmed","ink":"#14442B","primary":"#2E7D4F","surface":"#EDF2E6","cream":"#FAF7EF","accent":"#D08C2E","body":"#3C5344","heading_font":"Plus Jakarta Sans","accent_font":"Caveat","sizes":{"feed":"1080x1350","story":"1080x1920"},"voice":"Warm, plain, parent to parent. Short sentences. No fear-mongering, no exclamation stacking, no emoji in headlines. Hindi-English mixing allowed in captions, not headlines."}'::jsonb,
  '{"whatsapp":{"enabled":true,"phone_number_id":"DEV_TEST_NUMBER"},"webchat":{"enabled":true,"widget_key":"alcadent"},"instagram":{"enabled":false},"voice":{"enabled":false}}'::jsonb,
  '{"inbox_url":"/inbox","notify_roles":["owner","manager"],"office_hours_only":false}'::jsonb,
  '{"ai_conversations_per_month":2000,"template_messages_per_month":500,"voice_minutes_per_month":0}'::jsonb
)
on conflict (tenant_id) do update set
  business = excluded.business,
  hours = excluded.hours,
  brand = excluded.brand,
  channels = excluded.channels,
  escalation = excluded.escalation,
  limits = excluded.limits;

-- Channel routing: inbound webhooks resolve the tenant through this table ----
insert into public.channel_identities (tenant_id, channel, external_id, display_name)
values
  ((select id from public.tenants where slug = 'alcadent'), 'whatsapp', 'DEV_TEST_NUMBER', 'Alcadent India WhatsApp'),
  ((select id from public.tenants where slug = 'alcadent'), 'webchat', 'alcadent', 'Alcadent India web widget')
on conflict (channel, external_id) do update set
  tenant_id = excluded.tenant_id,
  display_name = excluded.display_name;

-- Bookable resources --------------------------------------------------------
insert into public.resources (tenant_id, slug, name)
values
  ((select id from public.tenants where slug = 'alcadent'), 'chair-1', 'Chair 1'),
  ((select id from public.tenants where slug = 'alcadent'), 'chair-2', 'Chair 2')
on conflict (tenant_id, slug) do update set name = excluded.name;

-- Services ------------------------------------------------------------------
insert into public.services (tenant_id, slug, name, description, duration_minutes, price_paise, price_is_estimate, recall_months)
values
  ((select id from public.tenants where slug = 'alcadent'), 'consultation', 'Consultation', 'First visit, examination and treatment plan discussion.', 30, 50000, true, 6),
  ((select id from public.tenants where slug = 'alcadent'), 'cleaning', 'Scaling & polishing', 'Routine cleaning for adults and older children.', 45, 150000, true, 6),
  ((select id from public.tenants where slug = 'alcadent'), 'kids-checkup', 'Kids check-up', 'Child-friendly examination with fluoride application if needed.', 30, 80000, true, 6),
  ((select id from public.tenants where slug = 'alcadent'), 'rct-sitting', 'Root canal sitting', 'Follow-up sitting for an in-progress root canal.', 60, null, true, null)
on conflict (tenant_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  duration_minutes = excluded.duration_minutes,
  price_paise = excluded.price_paise,
  price_is_estimate = excluded.price_is_estimate,
  recall_months = excluded.recall_months,
  active = true;

-- Agents: rows, not code. Adding one needs no deploy. -----------------------
insert into public.agents (
  tenant_id, slug, name, description, system_prompt_template,
  tool_allowlist, trigger, trigger_config, escalation_rule, tenant_variables, model_hint
)
values
  ((select id from public.tenants where slug = 'alcadent'), 'front-desk', 'Front Desk', 'Answers enquiries around the clock in the customer''s language, and books appointments.',
   'You are the front desk assistant for {{business_name}}, {{tagline}}.

Facts you may state:
- Address: {{address}}
- Opening hours: {{hours_summary}}
- Services and indicative prices:
{{services_summary}}

How to reply:
- Match the customer''s language. Hindi, English or a natural mix of both is fine.
- Short sentences. Warm and plain. No exclamation stacking, no emoji in the first line.
- If you do not know something, say so and offer to have the team confirm.

Hard limits:
{{boundaries}}

When someone wants an appointment, collect the name, the service and a preferred day and time, then use the booking tools. Confirm back in one short message.

If the customer is distressed, asks for a human, or asks anything outside these limits, escalate to the team.',
   array['search_knowledge', 'list_services', 'find_slots', 'create_booking', 'escalate_to_human'], 'inbound_message'::public.agent_trigger,
   '{"channels":["whatsapp","webchat"]}'::jsonb, '{"on_low_confidence":true}'::jsonb,
   '{"business_name":"Alcadent India","tagline":"Kids & Adult Dentistry","content_approver":"Dr. Anukriti Gupta","never_claim":"guaranteed outcomes, \"best in Gurugram\" style superlatives, or any unconfirmed price or treatment duration","boundaries":"- You do not diagnose, do not interpret symptoms, x-rays or photographs, and do not recommend treatment. Those questions go to Dr. Anukriti Gupta — offer an appointment.\n- You do not quote a final price or a treatment duration. Prices given are indicative and confirmed at the clinic after examination.\n- No superlatives (\"best in Gurugram\"), no guaranteed outcomes.\n- General oral-hygiene information (brushing, flossing, sugar, routine check-up frequency) is fine."}'::jsonb, 'claude-haiku-4-5-20251001'),
  ((select id from public.tenants where slug = 'alcadent'), 'recall', 'Recall Agent', 'Follow-ups that are due: periodic check-ups, pending sittings, repeat services.',
   'You write a single short recall message for {{business_name}}.

Context: {{recall_context}}

Rules:
- One message, under 350 characters, in the customer''s language.
- Warm, not pushy. State what is due and offer two concrete time options.
- Never imply a finding, urgency or risk. No fear-mongering.
{{boundaries}}
- Always include how to opt out: "Reply STOP to stop reminders."',
   array['list_services', 'find_slots', 'escalate_to_human'], 'schedule'::public.agent_trigger,
   '{"cron":"0 4 * * *","lookback_months":6}'::jsonb, '{"requires_consent":true,"max_attempts":2}'::jsonb,
   '{"business_name":"Alcadent India","tagline":"Kids & Adult Dentistry","content_approver":"Dr. Anukriti Gupta","never_claim":"guaranteed outcomes, \"best in Gurugram\" style superlatives, or any unconfirmed price or treatment duration","boundaries":"- You do not diagnose, do not interpret symptoms, x-rays or photographs, and do not recommend treatment. Those questions go to Dr. Anukriti Gupta — offer an appointment.\n- You do not quote a final price or a treatment duration. Prices given are indicative and confirmed at the clinic after examination.\n- No superlatives (\"best in Gurugram\"), no guaranteed outcomes.\n- General oral-hygiene information (brushing, flossing, sugar, routine check-up frequency) is fine."}'::jsonb, 'claude-haiku-4-5-20251001'),
  ((select id from public.tenants where slug = 'alcadent'), 'content-studio', 'Content Studio', 'Weekly carousels, reel scripts and story frames in the brand kit, held for approval before publishing.',
   'You draft social content for {{business_name}} in its brand voice.

Voice: {{brand_voice}}

Formats: {{content_sizes}}

Never claim: {{never_claim}}. Never state a price or duration that is not in:
{{services_summary}}

Hard limits:
{{boundaries}}

Every draft that touches a regulated topic is marked pending_approval. You do not publish. You produce a draft and a one-line note on what {{content_approver}} should check.',
   array['search_knowledge', 'list_services', 'create_content_draft'], 'schedule'::public.agent_trigger,
   '{"cron":"0 3 * * 1"}'::jsonb, '{"requires_approval":true,"approver":"{{content_approver}}"}'::jsonb,
   '{"business_name":"Alcadent India","tagline":"Kids & Adult Dentistry","content_approver":"Dr. Anukriti Gupta","never_claim":"guaranteed outcomes, \"best in Gurugram\" style superlatives, or any unconfirmed price or treatment duration","boundaries":"- You do not diagnose, do not interpret symptoms, x-rays or photographs, and do not recommend treatment. Those questions go to Dr. Anukriti Gupta — offer an appointment.\n- You do not quote a final price or a treatment duration. Prices given are indicative and confirmed at the clinic after examination.\n- No superlatives (\"best in Gurugram\"), no guaranteed outcomes.\n- General oral-hygiene information (brushing, flossing, sugar, routine check-up frequency) is fine."}'::jsonb, 'claude-sonnet-5')
on conflict (tenant_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  system_prompt_template = excluded.system_prompt_template,
  tool_allowlist = excluded.tool_allowlist,
  trigger = excluded.trigger,
  trigger_config = excluded.trigger_config,
  escalation_rule = excluded.escalation_rule,
  tenant_variables = excluded.tenant_variables,
  model_hint = excluded.model_hint;

-- Knowledge: the approved facts agents may quote ----------------------------
delete from public.knowledge_chunks
where tenant_id = (select id from public.tenants where slug = 'alcadent')
  and metadata ->> 'managed_by' = 'onboarding';

insert into public.knowledge_chunks (tenant_id, source, title, content, metadata)
values
  ((select id from public.tenants where slug = 'alcadent'), 'clinic_facts', 'Opening hours', 'Alcadent India is open seven days a week. Monday to Saturday 10:00 to 20:00, Sunday 11:00 to 17:00. Walk-ins are accepted but an appointment is faster.', '{"managed_by":"onboarding","approved_by":"clinic"}'::jsonb),
  ((select id from public.tenants where slug = 'alcadent'), 'clinic_facts', 'Location and parking', 'F-49, First Floor, Elan Miracle Mall, Sector 84, Gurugram 122004. Parking is available in the mall basement. The clinic is on the first floor, near the atrium lifts.', '{"managed_by":"onboarding","approved_by":"clinic"}'::jsonb),
  ((select id from public.tenants where slug = 'alcadent'), 'clinic_facts', 'Anxious children', 'The clinic uses a painless injection technique and offers conscious sedation for children who are very anxious. Parents can stay with the child during the visit. A first visit is usually a short, friendly familiarisation appointment.', '{"managed_by":"onboarding","approved_by":"clinic"}'::jsonb),
  ((select id from public.tenants where slug = 'alcadent'), 'oral_hygiene', 'Brushing for children', 'Children should brush twice a day with a pea-sized amount of fluoride toothpaste, with adult supervision until about age seven. Replace the brush every three months. Limit sugary drinks between meals.', '{"managed_by":"onboarding","approved_by":"clinic"}'::jsonb);

-- WhatsApp message templates (submitted to Meta separately) -----------------
insert into public.templates (tenant_id, name, language, category, body, variables)
values
  ((select id from public.tenants where slug = 'alcadent'), 'recall_six_month', 'en', 'utility', 'Hi {{1}}, it has been six months since your last visit to Alcadent. Would you like to book a check-up? Reply STOP to stop reminders.', array['customer_name']),
  ((select id from public.tenants where slug = 'alcadent'), 'appointment_reminder', 'en', 'utility', 'Hi {{1}}, reminder of your appointment at Alcadent on {{2}}. Reply RESCHEDULE if you need a different time.', array['customer_name', 'appointment_time'])
on conflict (tenant_id, name, language) do update set
  category = excluded.category,
  body = excluded.body,
  variables = excluded.variables;
