/**
 * Turns a tenant profile into idempotent SQL.
 *
 * One code path produces both the applied statements and `supabase/seed.sql`,
 * so the local stack and a live project can never drift. Every statement is an
 * upsert keyed on a natural unique constraint, and nothing references a
 * generated id directly — rows look the tenant up by slug — so running it twice
 * changes nothing.
 */
import type { AgentTemplate, TenantProfile } from '@/lib/onboarding/schema';

/**
 * Quotes a value as a SQL string literal.
 *
 * Profiles come from a repo file rather than a request, but they are edited by
 * Cowork and by hand, so a stray apostrophe must not be able to end a literal.
 * Null bytes are rejected outright: Postgres cannot store them in text and
 * they are a classic way to smuggle past a naive check.
 */
export function quote(value: string): string {
  if (value.includes('\0')) {
    throw new Error('Refusing to emit SQL for a value containing a null byte.');
  }
  return `'${value.replace(/'/g, "''")}'`;
}

export function quoteNullable(value: string | null | undefined): string {
  return value === null || value === undefined ? 'null' : quote(value);
}

export function quoteJson(value: unknown): string {
  return `${quote(JSON.stringify(value ?? {}))}::jsonb`;
}

/** Postgres text[] literal, e.g. array['a','b'] — or an empty typed array. */
export function quoteTextArray(values: string[]): string {
  if (values.length === 0) return `'{}'::text[]`;
  return `array[${values.map(quote).join(', ')}]`;
}

export function quoteNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  if (!Number.isFinite(value)) {
    throw new Error(`Refusing to emit SQL for a non-finite number: ${value}`);
  }
  return String(value);
}

/** A sub-select, so every child row finds its tenant by slug rather than by a baked-in uuid. */
function tenantRef(slug: string): string {
  return `(select id from public.tenants where slug = ${quote(slug)})`;
}

export interface BuildOptions {
  /** Link this already-registered auth user to the tenant as its owner. */
  ownerEmail?: string;
}

export function buildProvisionSql(
  profile: TenantProfile,
  templates: Map<string, AgentTemplate>,
  options: BuildOptions = {},
): string {
  const ref = tenantRef(profile.slug);
  const out: string[] = [];

  out.push(`-- Generated by scripts/onboard.ts from config/tenants/${profile.slug}.json.
-- Do not edit by hand: edit the profile and re-run \`npm run seed:build\`.
-- Every statement is an upsert, so applying this twice is a no-op.`);

  out.push(`
-- Tenant --------------------------------------------------------------------
insert into public.tenants (id, slug, name, vertical, plan, status, timezone, locale)
values (
  ${profile.id ? quote(profile.id) : 'gen_random_uuid()'},
  ${quote(profile.slug)},
  ${quote(profile.name)},
  ${quote(profile.vertical)},
  ${quote(profile.plan)}::public.plan_tier,
  ${quote(profile.status)}::public.tenant_status,
  ${quote(profile.timezone)},
  ${quote(profile.locale)}
)
on conflict (slug) do update set
  name = excluded.name,
  vertical = excluded.vertical,
  plan = excluded.plan,
  status = excluded.status,
  timezone = excluded.timezone,
  locale = excluded.locale;`);

  out.push(`
-- Configuration -------------------------------------------------------------
insert into public.tenant_config (tenant_id, business, hours, brand, channels, escalation, limits)
values (
  ${ref},
  ${quoteJson(profile.business)},
  ${quoteJson(profile.hours)},
  ${quoteJson(profile.brand)},
  ${quoteJson(profile.channels)},
  ${quoteJson(profile.escalation)},
  ${quoteJson(profile.limits)}
)
on conflict (tenant_id) do update set
  business = excluded.business,
  hours = excluded.hours,
  brand = excluded.brand,
  channels = excluded.channels,
  escalation = excluded.escalation,
  limits = excluded.limits;`);

  const identities: { channel: string; externalId: string; label: string }[] = [];
  if (profile.channels.whatsapp.enabled && profile.channels.whatsapp.phone_number_id) {
    identities.push({
      channel: 'whatsapp',
      externalId: profile.channels.whatsapp.phone_number_id,
      label: `${profile.name} WhatsApp`,
    });
  }
  if (profile.channels.webchat.enabled && profile.channels.webchat.widget_key) {
    identities.push({
      channel: 'webchat',
      externalId: profile.channels.webchat.widget_key,
      label: `${profile.name} web widget`,
    });
  }
  if (profile.channels.instagram.enabled && profile.channels.instagram.page_id) {
    identities.push({
      channel: 'instagram',
      externalId: profile.channels.instagram.page_id,
      label: `${profile.name} Instagram`,
    });
  }

  if (identities.length > 0) {
    out.push(`
-- Channel routing: inbound webhooks resolve the tenant through this table ----
insert into public.channel_identities (tenant_id, channel, external_id, display_name)
values
${identities
  .map((i) => `  (${ref}, ${quote(i.channel)}, ${quote(i.externalId)}, ${quote(i.label)})`)
  .join(',\n')}
on conflict (channel, external_id) do update set
  tenant_id = excluded.tenant_id,
  display_name = excluded.display_name;`);
  }

  if (profile.resources.length > 0) {
    out.push(`
-- Bookable resources --------------------------------------------------------
insert into public.resources (tenant_id, slug, name)
values
${profile.resources.map((r) => `  (${ref}, ${quote(r.slug)}, ${quote(r.name)})`).join(',\n')}
on conflict (tenant_id, slug) do update set name = excluded.name;`);
  }

  if (profile.services.length > 0) {
    out.push(`
-- Services ------------------------------------------------------------------
insert into public.services (tenant_id, slug, name, description, duration_minutes, price_paise, price_is_estimate, recall_months)
values
${profile.services
  .map(
    (s) =>
      `  (${ref}, ${quote(s.slug)}, ${quote(s.name)}, ${quoteNullable(s.description)}, ` +
      `${quoteNumber(s.duration_minutes)}, ${quoteNumber(s.price_paise)}, ${s.price_is_estimate}, ${quoteNumber(s.recall_months)})`,
  )
  .join(',\n')}
on conflict (tenant_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  duration_minutes = excluded.duration_minutes,
  price_paise = excluded.price_paise,
  price_is_estimate = excluded.price_is_estimate,
  recall_months = excluded.recall_months,
  active = true;`);
  }

  const agents = profile.agents
    .map((agentSlug) => templates.get(agentSlug))
    .filter((template): template is AgentTemplate => Boolean(template));

  if (agents.length > 0) {
    out.push(`
-- Agents: rows, not code. Adding one needs no deploy. -----------------------
insert into public.agents (
  tenant_id, slug, name, description, system_prompt_template,
  tool_allowlist, trigger, trigger_config, escalation_rule, tenant_variables, model_hint
)
values
${agents
  .map(
    (a) =>
      `  (${ref}, ${quote(a.slug)}, ${quote(a.name)}, ${quote(a.description)},\n` +
      `   ${quote(a.system_prompt_template)},\n` +
      `   ${quoteTextArray(a.tool_allowlist)}, ${quote(a.trigger)}::public.agent_trigger,\n` +
      `   ${quoteJson(a.trigger_config)}, ${quoteJson(a.escalation_rule)},\n` +
      `   ${quoteJson(profile.agent_variables)}, ${quoteNullable(a.model_hint)})`,
  )
  .join(',\n')}
on conflict (tenant_id, slug) do update set
  name = excluded.name,
  description = excluded.description,
  system_prompt_template = excluded.system_prompt_template,
  tool_allowlist = excluded.tool_allowlist,
  trigger = excluded.trigger,
  trigger_config = excluded.trigger_config,
  escalation_rule = excluded.escalation_rule,
  tenant_variables = excluded.tenant_variables,
  model_hint = excluded.model_hint;`);
  }

  if (profile.knowledge.length > 0) {
    // knowledge_chunks has no natural key, so replace the generated set wholesale
    // rather than accumulating duplicates on every run. Chunks added through the
    // portal carry a different source and are left alone.
    out.push(`
-- Knowledge: the approved facts agents may quote ----------------------------
delete from public.knowledge_chunks
where tenant_id = ${ref}
  and metadata ->> 'managed_by' = 'onboarding';

insert into public.knowledge_chunks (tenant_id, source, title, content, metadata)
values
${profile.knowledge
  .map(
    (k) =>
      `  (${ref}, ${quote(k.source)}, ${quoteNullable(k.title)}, ${quote(k.content)}, ` +
      `${quoteJson({ managed_by: 'onboarding', approved_by: k.approved_by ?? null })})`,
  )
  .join(',\n')};`);
  }

  if (profile.message_templates.length > 0) {
    out.push(`
-- WhatsApp message templates (submitted to Meta separately) -----------------
insert into public.templates (tenant_id, name, language, category, body, variables)
values
${profile.message_templates
  .map(
    (t) =>
      `  (${ref}, ${quote(t.name)}, ${quote(t.language)}, ${quote(t.category)}, ` +
      `${quote(t.body)}, ${quoteTextArray(t.variables)})`,
  )
  .join(',\n')}
on conflict (tenant_id, name, language) do update set
  category = excluded.category,
  body = excluded.body,
  variables = excluded.variables;`);
  }

  if (options.ownerEmail) {
    out.push(`
-- Owner: links an existing Supabase Auth account to this tenant -------------
insert into public.users (tenant_id, auth_user_id, email, role)
select ${ref}, u.id, u.email, 'owner'::public.user_role
from auth.users u
where lower(u.email) = lower(${quote(options.ownerEmail)})
on conflict (tenant_id, auth_user_id) do update set
  role = 'owner'::public.user_role,
  disabled_at = null;`);
  }

  return `${out.join('\n')}\n`;
}
